name: Build & Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:

  build:

    runs-on: macOS-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Install
      run: pod install
    - name: Build & Test
      run: xcodebuild test -workspace sf-ios.xcworkspace -scheme sf-ios -destination 'platform=iOS Simulator,OS=latest,name=iPhone 16'
